spring:
  application:
    name: ms-authentication
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

security:
  jwt:
    secret: "${JWT_SECRET:M1Qu3r1d0N4P0L30Nk41s3r12345678901234567890}" # 512 bits
    expiration: "${JWT_DURATION:2700000}" # 45 minutes in milliseconds

logging:
  level:
    com.kodenca.ms_authentication: DEBUG
    org.springframework.security: DEBUG
