package com.kodenca.ms_authentication.mapper;

import com.kodenca.ms_authentication.dto.request.RegisterRequest;
import com.kodenca.ms_authentication.dto.response.AuthResponse;
import com.kodenca.ms_authentication.entity.UserEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface IUserMapper {
    
    @Mapping(target = "userUuId", ignore = true) // Generated by @PrePersist
    @Mapping(target = "enabled", constant = "true")
    @Mapping(target = "userName", source = "userName")
    @Mapping(target = "password", ignore = true) // set in service
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    UserEntity toEntity(RegisterRequest request);
    
    AuthResponse toAuthResponse(String token);
}
